name: espaço no arquivo
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited
    paths-ignore:
      - '.github/workflows/**'

jobs:
  validar-trecho:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Configurar variável de ambiente GH_TOKEN
      run: echo "GH_TOKEN=${{ secrets.GH_TOKEN }}" >> $GITHUB_ENV 

    - name: Verificar Conteúdo do PR
      run: |

        arquivos_adicionados=($(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep " "))
        #echo "##########################arquivos_adicionados###################################  $arquivos_adicionados"

        encontrada=false  # Inicializa encontrada como falso fora do loop
        saida=""  # Inicializa a variável de saída

        
          echo "Validando arquivo adicionado: $arquivos_adicionados"

          if [ -n "$arquivos_adicionados" ]; then
            echo "Erro: Os seguintes arquivos têm espaços em seus nomes:"
            echo "$arquivos_adicionados"
            saida="$saida$arquivos_adicionados"'\n'
            encontrada=true
          fi

          #echo "##########################contagem depois do if###################################  $contagem"
                 
        if [ "$encontrada" == true ]; then
          echo "::warning::Um ou mais nome de arquivos no pull request contém espaço"
          SLACK_MESSAGE="Label 'bug' adicionada ao PR: ${{ github.event.number }} - github.com/${GITHUB_REPOSITORY}/pull/${{ github.event.number }}/files (${{ github.base_ref }})\n"
          curl -X POST -H 'Content-type: application/json' --data '{"text":"'"$SLACK_MESSAGE"'"}' ${{ secrets.SLACK_WEBHOOK_URL }}
          PR_NUMBER=$(echo "${{ github.event.pull_request.html_url }}" | awk -F'/' '{print $NF}')
          REPO_OWNER=$(echo "${{ github.repository }}" | cut -d '/' -f 1)
          REPO_NAME=$(echo "${{ github.repository }}" | cut -d '/' -f 2)
          AUTHOR_NAME=${{ github.event.pull_request.user.login }}
          gh pr comment $PR_NUMBER -R $REPO_OWNER/$REPO_NAME --body "@$AUTHOR_NAME por favor revisar"
          exit 0
        fi
