name: index tablespace
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited
    paths-ignore:
      - '.github/workflows/**'

jobs:
  validar-tablespace:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Configurar variável de ambiente GH_TOKEN
      run: echo "GH_TOKEN=${{ secrets.GH_TOKEN }}" >> $GITHUB_ENV 

    - name: Obter conteúdo do pull request
      id: obter-conteudo
      run: |
        encontrada=false
        saida=""

        echo "Pull request acabou de ser aberto. Verificando novos arquivos adicionados."

        # Obtém a lista de arquivos adicionados no pull request
        arquivos_adicionados=($(git diff --name-only HEAD^1))
        echo "Arquivos adicionados: ${arquivos_adicionados[@]}"

        for arquivo in "${arquivos_adicionados[@]}"; do
          echo "Verificando o arquivo: $arquivo"

          if awk '/create index/ && !/tablespace/' "$arquivo" | grep -q "."; then
            encontrada=true
            saida="$saida$arquivo"$'\n'
          else
             echo "index OK"
          fi
        done

        if [ "$encontrada" == true ]; then
          echo "::error::Criação de índice sem tablespace"
          SLACK_MESSAGE="Criação de índice sem tablespace no PR - ${{ github.event.number }} - github.com/${GITHUB_REPOSITORY}/pull/${{ github.event.number }}/files (${{ github.base_ref }})\n$saida"
          curl -X POST -H 'Content-type: application/json' --data '{"text":"'"$SLACK_MESSAGE"'"}' ${{ secrets.SLACK_WEBHOOK_URL }}
          PR_NUMBER=$(echo "${{ github.event.pull_request.html_url }}" | awk -F'/' '{print $NF}')
          REPO_OWNER=$(echo "${{ github.repository }}" | cut -d '/' -f 1)
          REPO_NAME=$(echo "${{ github.repository }}" | cut -d '/' -f 2)
          AUTHOR_NAME=${{ github.event.pull_request.user.login }}
          gh pr comment $PR_NUMBER -R $REPO_OWNER/$REPO_NAME --body "@$AUTHOR_NAME
          Criação de índice sem tablespace
          ${saida}Por favor revisar."
          
          else
          echo "PR OK"
        fi
  validar-barra:
    runs-on: ubuntu-latest
    needs: validar-tablespace
    steps:
    - name: Obter conteúdo do pull request
      id: obter-conteudo
      run: |
        encontrada=false
        saida=""

        echo "Pull request acabou de ser aberto. Verificando novos arquivos adicionados."

        # Obtém a lista de arquivos adicionados no pull request
        arquivos_adicionados=($(git diff --name-only HEAD^1))
        echo "Arquivos adicionados: ${arquivos_adicionados[@]}"

        for arquivo in "${arquivos_adicionados[@]}"; do
          echo "Verificando o arquivo: $arquivo"

        if grep -Ei -q 'create trigger|create or replace trigger' "$arquivo"; then
        echo "Validando arquivo adicionado: $arquivo"
        check=$(awk '/END.*;$/ {flag=1; next} /^\/$/ {if(flag){print "Encontrado ;/ no arquivo"}} {flag=0}' "$arquivo")
        if [[ -n "$check" ]]; then
            echo "O arquivo $arquivo está no formato correto com ;/ no final."
        else
            echo "O arquivo $arquivo não tem ;/ no final, ou está mal formatado."
            encontrada=true
            saida+="$saida$arquivo"$'\n'
        fi
        fi
        done

        if [ "$encontrada" == true ]; then
          echo "::error::Criação de trigger sem barra ( / )"
          SLACK_MESSAGE="Criação de trigger sem barra ( / ) no PR - ${{ github.event.number }} - github.com/${GITHUB_REPOSITORY}/pull/${{ github.event.number }}/files (${{ github.base_ref }})\n$saida"
          curl -X POST -H 'Content-type: application/json' --data '{"text":"'"$SLACK_MESSAGE"'"}' ${{ secrets.SLACK_WEBHOOK_URL }}
          PR_NUMBER=$(echo "${{ github.event.pull_request.html_url }}" | awk -F'/' '{print $NF}')
          REPO_OWNER=$(echo "${{ github.repository }}" | cut -d '/' -f 1)
          REPO_NAME=$(echo "${{ github.repository }}" | cut -d '/' -f 2)
          AUTHOR_NAME=${{ github.event.pull_request.user.login }}
          gh pr comment $PR_NUMBER -R $REPO_OWNER/$REPO_NAME --body "@$AUTHOR_NAME
          Criação de trigger sem barra (/)
          ${saida}Trigger deve finalizar com ; e /
          Por favor revisar."
          exit 1
          else
          echo "PR OK"
        fi
