name: Validar Extensão de Arquivos no Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths-ignore:
      - '.github/workflows/**'

jobs:
  validar-extensao:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Listar arquivos do pull request
      id: listar-arquivos
      run: |
        git diff --name-only ${{ github.event.before }} ${{ github.sha }} > files.txt
        cat files.txt

    - name: Verificar extensão de arquivos
      run: |
        tem_erro=false
        saida=""

        for arquivo in $(cat files.txt); do
          if [[ -f "$arquivo" || "$arquivo" != *.* ]]; then
            echo "############arquivo###########  $arquivo"
            echo "ERRO: O arquivo $arquivo não tem uma extensão. Todos os arquivos devem ter extensão."
            tem_erro=true
            saida="$saida$arquivo\n"
            echo "##########saida########### $saida"
          fi
        done

        if [ "$tem_erro" = true ]; then
          echo "Enviando notificação para o Slack..."
          curl -X POST -H 'Content-type: application/json' --data '{"text":"ERRO: Um ou mais arquivos no pull request têm extensão. Todos os arquivos devem ter extensão.\n'$(cat $saida)'}' ${{ secrets.SLACK_WEBHOOK_URL }}
          exit 1
        else
          echo "Todos os arquivos tem extensão."
        fi
