name: Caracteres especiais
on:
  push:
    branches:
      - main

jobs:
  validar-caracteres:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configurar variável de ambiente GH_TOKEN
        run: echo "GH_TOKEN=${{ secrets.GH_TOKEN }}" >> $GITHUB_ENV

      - name: Obter lista de arquivos alterados
        run: |
          set -x
          branch=$(echo "${{ github.ref }}" | awk -F'/' '{print $NF}')
          #commit_number=$(${{ github.sha }})
          # Obter a lista de arquivos alterados no push
          arquivos_alterados=($(git diff --name-only HEAD^1))

          # Adicionar ação para validar nome de arquivo com caracteres especiais
          for arquivo in "${arquivos_alterados[@]}"; do
            if [[ "$arquivo" =~ [^a-zA-Z0-9_\.-] ]]; then
              echo "::error::Existe nome de arquivo com caracteres especiais no push: $arquivo"
              encontrado=true
            fi
          done
          
          if [ "$encontrado" == true ]; then
            echo "Arquivo(s) com caracteres especiais encontrados. Commit bloqueado."
            
            # Enviar notificação para o Slack
            SLACK_MESSAGE="Existe nome de arquivo com caracteres especiais no push\nhttps://github.com/${GITHUB_REPOSITORY}/commit/${{ github.sha }} ($branch) <@evandson.cruz>"
            curl -X POST -H 'Content-type: application/json' --data '{"text":"'"$SLACK_MESSAGE"'"}' ${{ secrets.SLACK_WEBHOOK_URL }}
            exit 1
          fi
