name: identifier too long

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited
    paths-ignore:
      - '.github/workflows/**'

jobs:
  validar-trecho:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Obter conteúdo do pull request
      id: obter-conteudo
      run: |
        if [[ "${{ github.event.action }}" == "opened" || "${{ github.event.action }}" == "reopened" ]]; then
          echo "$(git diff --name-only HEAD^1)"
          #echo "########################### $conteudo_pr"
        else
          #conteudo_pr=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          #echo "########################### $conteudo_pr"
        fi
        
        tem_erro=false
        saida=""

        #echo "########################### ${{ conteudo_pr }}"

        

        
