name: index tablespace
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited
    paths-ignore:
      - '.github/workflows/**'

jobs:
  validar-fim-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Configurar variável de ambiente GH_TOKEN
      run: echo "GH_TOKEN=${{ secrets.GH_TOKEN }}" >> $GITHUB_ENV 

    - name: Obter conteúdo do pull request
      id: obter-conteudo
      run: |
        palavras_chave=("create index")  # Substitua pela lista de palavras-chave desejada
        outras_palavras=("tablespace")  # Substitua pela segunda lista de palavras 

        encontrada=true 
        saida=""

        echo ">>>>>>>>>antes do for>>>>>>>>>>> $encontrada"
        echo "#############################################################  ${{ github.event_name }}"
        echo "##########################opened###################################  ${{ github.event.action }}"
        
        echo "Pull request acabou de ser aberto. Verificando novos arquivos adicionados."

        # Obtém a lista de arquivos adicionados no pull request
        arquivos_adicionados=($(git diff --name-only HEAD^1))
        echo "##########################arquivos_adicionados###################################  $arquivos_adicionados"

        for arquivo in "${arquivos_adicionados[@]}"; do
          echo "Novo arquivo adicionado: $arquivo"

          # Restante do seu código para verificar palavras-chave e outras_palavras
          for palavra_chave in "${palavras_chave[@]}"; do
            if grep -q "$palavra_chave" "$arquivo"; then
              echo "Encontrada a palavra '$palavra_chave' no novo arquivo: $arquivo"
              
              # Verificar se a outra palavra-chave está presente no mesmo bloco do CREATE INDEX
              encontrada_outra_palavra=false
              while IFS= read -r linha; do
                if [[ "$linha" == "create index"* ]]; then
                  encontrada_outra_palavra=true
                elif [ "$encontrada_outra_palavra" == true ] && [[ "$linha" == *"tablespace"* ]]; then
                  encontrada_outra_palavra=false
                fi
              done < "$arquivo"

              if [ "$encontrada_outra_palavra" == false ]; then
                echo "Encontrada a palavra 'tablespace' para o CREATE INDEX no mesmo arquivo: $arquivo"
                encontrada=false
                saida="$saida$arquivo"$'\n'
              fi
            fi
          done
        done

        echo ">>>>>>>depois do for>>>>>>>>>>>>> $encontrada"

       
