name: espaço no arquivo
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited
    paths-ignore:
      - '.github/workflows/**'

jobs:
  validar-trecho:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Configurar variável de ambiente GH_TOKEN
      run: echo "GH_TOKEN=${{ secrets.GH_TOKEN }}" >> $GITHUB_ENV 

    - name: Verificar Conteúdo do PR
      run: |
        
        encontrada=false 
        saida=""

        echo ">>>>>>>>>antes do for>>>>>>>>>>> $encontrada"
        echo "#############################################################  ${{ github.event_name }}"
        echo "##########################opened###################################  ${{ github.event.action }}"
        
       
          echo "Pull request acabou de ser aberto. Verificando novos arquivos adicionados."

          # Obtém a lista de arquivos adicionados no pull request
          arquivos_adicionados=git diff --name-only HEAD^1 | while IFS= read -r arquivo; do
          echo "##########################arquivos_adicionados###################################  $arquivos_adicionados"

          for arquivo in "${arquivos_adicionados[@]}"; do
            echo "Novo arquivo adicionado: $arquivo"

            # Verificar se o nome do arquivo contém espaços
            if [[ "$arquivo" == *" "* ]]; then
              echo "O nome do arquivo '$arquivo' contém espaços."
              encontrada=true
              saida="$saida$arquivo"$'\n'
            else
              echo "O nome do arquivo '$arquivo' não contém espaços."
            fi
                
        echo ">>>>>>>depois do for>>>>>>>>>>>>> $encontrada"
        
        if [ "$encontrada" == true ]; then
          echo "::warning::Um ou mais nome de arquivos no pull request contém espaço"
          SLACK_MESSAGE="Label 'bug' adicionada ao PR: ${{ github.event.number }} - github.com/${GITHUB_REPOSITORY}/pull/${{ github.event.number }}/files (${{ github.base_ref }})\n$saida"
          curl -X POST -H 'Content-type: application/json' --data '{"text":"'"$SLACK_MESSAGE"'"}' ${{ secrets.SLACK_WEBHOOK_URL }}
          PR_NUMBER=$(echo "${{ github.event.pull_request.html_url }}" | awk -F'/' '{print $NF}')
          REPO_OWNER=$(echo "${{ github.repository }}" | cut -d '/' -f 1)
          REPO_NAME=$(echo "${{ github.repository }}" | cut -d '/' -f 2)
          AUTHOR_NAME=${{ github.event.pull_request.user.login }}
          gh pr comment $PR_NUMBER -R $REPO_OWNER/$REPO_NAME --body "@$AUTHOR_NAME por favor revisar"
          exit 0
        fi
