name: Validar colunas auditoria
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
  validar-colunas:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
    
    - name: Configurar variável de ambiente GH_TOKEN
      run: echo "GH_TOKEN=${{ secrets.GH_TOKEN }}" >> $GITHUB_ENV 

    - name: Obter lista de arquivos alterados
      run: |
        problemas=false
        mensagem_erro=""

        colunas=("DT_ATLZ" "DT_CRIACAO" "USUARIO_CRIACAO" "USUARIO_ATUALIZACAO")
        arquivos_alterados=$(git diff --name-only HEAD^1)

        for arquivo in $arquivos_alterados; do
          if grep -qiE 'CREATE TABLE' "$arquivo"; then
            colunas_faltando=()
            for coluna in "${colunas[@]}"; do
              if ! grep -qiE "$coluna" "$arquivo"; then
                problemas=true
                colunas_faltando+=("$coluna")
              fi
            done
            if [ ${#colunas_faltando[@]} -ne 0 ]; then
              colunas_faltando_str=""
              for coluna in "${colunas_faltando[@]}"; do
                colunas_faltando_str+="$coluna, "
              done
              colunas_faltando_str=${colunas_faltando_str%, } # Remove a última vírgula e espaço
              mensagem_erro+="Arquivo: $arquivo, Colunas faltando: $colunas_faltando_str\n"
            fi
          fi
        done

        if [ "$problemas" = true ]; then
          mensagem_erro=$(echo -e "$mensagem_erro" | sed 's/\n$//')

          echo "::error::A criação de tabela não tem todos os campos de auditoria necessários: $mensagem_erro"

          SLACK_MESSAGE="PR ${{ github.event.number }} - github.com/${{ github.repository }}/pull/${{ github.event.number }}/files (${{ github.base_ref }})\n\nA criação da tabela nos seguintes arquivos não tem todos os campos de auditoria necessários:\n$mensagem_erro"

          curl -X POST -H 'Content-type: application/json' --data '{"text":"'"$SLACK_MESSAGE"'"}' ${{ secrets.SLACK_WEBHOOK_URL }}
          
          PR_NUMBER=$(echo "${{ github.event.pull_request.html_url }}" | awk -F'/' '{print $NF}')
          REPO_OWNER=$(echo "${{ github.repository }}" | cut -d '/' -f 1)
          REPO_NAME=$(echo "${{ github.repository }}" | cut -d '/' -f 2)
          AUTHOR_NAME=${{ github.event.pull_request.user.login }}
          
          gh pr comment $PR_NUMBER -R $REPO_OWNER/$REPO_NAME --body "@$AUTHOR_NAME

          A criação da tabela nos seguintes arquivos não tem todos os campos de auditoria necessários:

        $mensagem_erro"
        exit 1
        else
          echo "PR OK"
        fi

  validar-conteudo:
    runs-on: ubuntu-latest
    needs: checkout 
    steps:
      
      - name: Configurar variável de ambiente GH_TOKEN
        run: echo "GH_TOKEN=${{ secrets.GH_TOKEN }}" >> $GITHUB_ENV 

      - name: Imprimir alterações
        run: |
          echo "Referência antes do evento: ${{ github.event.before }}"
          echo "SHA do commit atual: ${{ github.sha }}"
          git diff --name-only ${{ github.event.before }} ${{ github.sha }}  

      - name: Verificar Conteúdo do PR
        run: |
          palavras_chave=("grant")  # Substitua pela lista de palavras-chave desejada
          outras_palavras=("to public")  # Substitua pela segunda lista de palavras 

          encontrada=false 
          saida=""

          echo ">>>>>>>>>antes do for>>>>>>>>>>> $encontrada"
          echo "#############################################################  ${{ github.event_name }}"
          echo "##########################opened###################################  ${{ github.event.action }}"
          
          if [ "${{ github.event.action }}" == "opened" ]; then
            echo "Pull request acabou de ser aberto. Verificando novos arquivos adicionados."

            # Obtém a lista de arquivos adicionados no pull request
            arquivos_adicionados=($(git diff --name-only HEAD^1))
            echo "##########################arquivos_adicionados###################################  $arquivos_adicionados"

            for arquivo in "${arquivos_adicionados[@]}"; do
              echo "Novo arquivo adicionado: $arquivo"

              # Restante do seu código para verificar palavras-chave e outras_palavras
              for palavra_chave in "${palavras_chave[@]}"; do
                if grep -q "$palavra_chave" "$arquivo"; then
                  echo "Encontrada a palavra '$palavra_chave' no novo arquivo: $arquivo"
                  for outra_palavra in "${outras_palavras[@]}"; do
                    if grep -q "$outra_palavra" "$arquivo"; then
                      echo "Encontrada a palavra '$outra_palavra' no mesmo arquivo: $arquivo"
                      encontrada=true
                      saida="$saida$palavra_chave $outra_palavra no arquivo $arquivo\n"
                    fi
                  done
                fi
              done
            done
          else 
            for arquivo in $(git diff --name-only ${{ github.event.before }} ${{ github.sha }}); do
              for palavra_chave in "${palavras_chave[@]}"; do
                if grep -q "$palavra_chave" "$arquivo"; then
                  echo "Encontrada a palavra '$palavra_chave' no arquivo: $arquivo"
                  for outra_palavra in "${outras_palavras[@]}"; do
                    if grep -q "$outra_palavra" "$arquivo"; then
                      echo "Encontrada a palavra '$outra_palavra' no mesmo arquivo: $arquivo"
                      encontrada=true
                      saida="$saida$palavra_chave $outra_palavra no arquivo $arquivo\n"
                    fi
                  done
                fi
              done
            done
          fi
          
          echo ">>>>>>>depois do for>>>>>>>>>>>>> $encontrada"

          if [ "$encontrada" == true ]; then
            SLACK_MESSAGE="Label 'bug' adicionada ao PR: ${{ github.event.number }} - github.com/${GITHUB_REPOSITORY}/pull/${{ github.event.number }}/files (${{ github.base_ref }})\n$saida"
            curl -X POST -H 'Content-type: application/json' --data '{"text":"'"$SLACK_MESSAGE"'"}' ${{ secrets.SLACK_WEBHOOK_URL }}
            exit 1
          fi
          

  validar-extensao:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
    
    - name: Configurar variável de ambiente GH_TOKEN
      run: echo "GH_TOKEN=${{ secrets.GH_TOKEN }}" >> $GITHUB_ENV

    - name: Listar arquivos do pull request
      id: listar-arquivos
      run: |
        
          git diff --name-only HEAD^1 > files.txt
          cat files.txt

    - name: Verificar extensão de arquivos
      run: |
        tem_erro=false
        saida=""

        for arquivo in $(cat files.txt); do
          if [[ "$arquivo" != *.* ]]; then
            echo "############arquivo###########  $arquivo"
            echo "ERRO: O arquivo $arquivo não tem uma extensão. Todos os arquivos devem ter extensão."
            tem_erro=true
            saida="$saida$arquivo"$'\n'
            echo "##########saida########### $saida"
          fi
        done

        if [ "$tem_erro" = true ]; then
          echo "Enviando notificação para o Slack..."
          #curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"ERRO: Um ou mais arquivos no pull request não tem extensão. Todos os arquivos devem ter extensão.\n${saida}\"}" ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_MESSAGE="ERRO: Todos os arquivos devem ter extensão. PR: ${{ github.event.number }} - github.com/${GITHUB_REPOSITORY}/pull/${{ github.event.number }}/files (${{ github.base_ref }})\nUm ou mais arquivos no pull request não tem extensão:\n$saida"
          curl -X POST -H 'Content-type: application/json' --data '{"text":"'"$SLACK_MESSAGE"'"}' ${{ secrets.SLACK_WEBHOOK_URL }}
          PR_NUMBER=$(echo "${{ github.event.pull_request.html_url }}" | awk -F'/' '{print $NF}')
          REPO_OWNER=$(echo "${{ github.repository }}" | cut -d '/' -f 1)
          REPO_NAME=$(echo "${{ github.repository }}" | cut -d '/' -f 2)
          AUTHOR_NAME=${{ github.event.pull_request.user.login }}
          gh pr comment $PR_NUMBER -R $REPO_OWNER/$REPO_NAME --body "@$AUTHOR_NAME
          Um ou mais arquivos não tem extensão:
          ${saida}Por favor revisar."
          exit 1
        else
          echo "Todos os arquivos tem extensão."
        fi
