name: Validar Commits nos Arquivos SQL
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited

jobs:
  validar-commits:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Configurar variável de ambiente GH_TOKEN
      run: echo "GH_TOKEN=${{ secrets.GH_TOKEN }}" >> $GITHUB_ENV 

    - name: Obter lista de arquivos alterados
      run: |
        # Obter a lista de arquivos alterados no pull request
        arquivos_alterados=($(git diff --name-only HEAD^1))

        # Contar o número de arquivos no pull request
        contagem_arquivos=${#arquivos_alterados[@]}  
        # Verificar se há mais de um arquivo no pull request
        if [ "$contagem_arquivos" -gt 1 ]; then
          # Obter a lista de arquivos no pull request
          arquivos=($(git diff --name-only HEAD^1))

          # Inicializar uma variável para rastrear se há mais de um commit
          mais_de_um_commit=true

          contagem_commits=$(gh pr view ${{ github.event.number }} --json commits -q '.commits | length')

          for arquivo in "${arquivos[@]}"; do
            # Verificar se o arquivo contém uma declaração CREATE TABLE
            if grep -qiE 'CREATE TABLE' "$arquivo"; then
              # Se o arquivo tiver mais de um commit, configurar a variável
              if [ "$contagem_commits" -lt 2 ]; then
                mais_de_um_commit=false
                # Validar se há mais de um commit em pelo menos um arquivo
                if [ "$mais_de_um_commit" == false ]; then
                echo "Erro: O pull request tem create table e mais de um arquivo, porém não tem mais de um commit. Crie um novo PR fazendo commits separados para garantir a ordem de execução e suas dependências"
                break
                else
                echo "O pull request tem mais de um commit."
                fi
              fi
            fi
          done
        fi

        if [ "$mais_de_um_commit" == false ]; then
          echo "::error::O pull request tem create table e mais de um arquivo, porém não tem mais de um commit. Crie um novo PR fazendo commits separados para garantir a ordem de execução e suas dependências"
          SLACK_MESSAGE="PR ${{ github.event.number }} - github.com/${GITHUB_REPOSITORY}/pull/${{ github.event.number }}/files (${{ github.base_ref }})\nO pull request tem create table e mais de um arquivo, porém não tem mais de um commit.\nCrie um novo PR fazendo commits separados para garantir a ordem de execução e suas dependências."
          curl -X POST -H 'Content-type: application/json' --data '{"text":"'"$SLACK_MESSAGE"'"}' ${{ secrets.SLACK_WEBHOOK_URL }}
          PR_NUMBER=$(echo "${{ github.event.pull_request.html_url }}" | awk -F'/' '{print $NF}')
          REPO_OWNER=$(echo "${{ github.repository }}" | cut -d '/' -f 1)
          REPO_NAME=$(echo "${{ github.repository }}" | cut -d '/' -f 2)
          AUTHOR_NAME=${{ github.event.pull_request.user.login }}
          gh pr comment $PR_NUMBER -R $REPO_OWNER/$REPO_NAME --body "@$AUTHOR_NAME
          O pull request tem create table e mais de um arquivo, porém não tem mais de um commit.
          Crie um novo PR fazendo commits separados para garantir a ordem de execução e suas dependências."
          gh pr close ${{ github.event.number }}
        else
          echo "PR OK"
        fi
