name: Validar colunas auditoria
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited

jobs:
  validar-colunas:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Configurar variável de ambiente GH_TOKEN
      run: echo "GH_TOKEN=${{ secrets.GH_TOKEN }}" >> $GITHUB_ENV 

    - name: Obter lista de arquivos alterados
      run: |
        problemas=false
        mensagem_erro=""

        colunas=("DT_ATLZ" "DT_CRIACAO" "USUARIO_CRIACAO" "USUARIO_ATUALIZACAO")
        arquivos_alterados=$(git diff --name-only HEAD^1)

        for arquivo in $arquivos_alterados; do
          if grep -qiE 'CREATE TABLE' "$arquivo"; then
            colunas_faltando=()
            for coluna in "${colunas[@]}"; do
              if ! grep -qiE "$coluna" "$arquivo"; then
                problemas=true
                colunas_faltando+=("$coluna")
              fi
            done
            if [ ${#colunas_faltando[@]} -ne 0 ]; then
              colunas_faltando_str=""
              for coluna in "${colunas_faltando[@]}"; do
                colunas_faltando_str+="$coluna, "
              done
              colunas_faltando_str=${colunas_faltando_str%, } # Remove a última vírgula e espaço
              mensagem_erro+="Arquivo: $arquivo, Colunas faltando: $colunas_faltando_str\n"
            fi
          fi
        done

        if [ "$problemas" = true ]; then
          mensagem_erro=$(echo -e "$mensagem_erro" | sed 's/\n$//')

          SLACK_MESSAGE="PR ${{ github.event.number }} - github.com/${{ github.repository }}/pull/${{ github.event.number }}/files (${{ github.base_ref }})\n\nA criação da tabela nos seguintes arquivos não tem todos os campos de auditoria necessários:\n$mensagem_erro"

          curl -X POST -H 'Content-type: application/json' --data '{"text":"'"$SLACK_MESSAGE"'"}' ${{ secrets.SLACK_WEBHOOK_URL }}
          
          PR_NUMBER=$(echo "${{ github.event.pull_request.html_url }}" | awk -F'/' '{print $NF}')
          REPO_OWNER=$(echo "${{ github.repository }}" | cut -d '/' -f 1)
          REPO_NAME=$(echo "${{ github.repository }}" | cut -d '/' -f 2)
          AUTHOR_NAME=${{ github.event.pull_request.user.login }}
          
          gh pr comment $PR_NUMBER -R $REPO_OWNER/$REPO_NAME --body "@$AUTHOR_NAME

          A criação da tabela nos seguintes arquivos não tem todos os campos de auditoria necessários:

        $mensagem_erro"
        exit 1
        else
          echo "PR OK"
        fi
