name: Validar Commits nos Arquivos SQL
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited

jobs:
  validar-commits:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Configurar variável de ambiente GH_TOKEN
      run: echo "GH_TOKEN=${{ secrets.GH_TOKEN }}" >> $GITHUB_ENV 

    - name: Obter lista de arquivos alterados
      run: |
        set -x
        # Obter a lista de arquivos alterados no pull request
        arquivos_alterados=($(git diff --name-only HEAD^1))

        # Contar o número de arquivos no pull request
        contagem_arquivos=${#arquivos_alterados[@]}  
        # Verificar se há mais de um arquivo no pull request
        if [ "$contagem_arquivos" -gt 1 ]; then
          # Obter a lista de arquivos SQL no pull request
          arquivos=($(git diff --name-only HEAD^1))

          # Inicializar uma variável para rastrear se há mais de um commit
          mais_de_um_commit=false

          contagem_commits=$(gh pr view ${{ github.event.number }} --json commits -q '.commits | length')

          echo "################################## $contagem_commits"

          for arquivo in "${arquivos[@]}"; do
            # Verificar se o arquivo contém uma declaração CREATE TABLE
            if grep -qiE 'CREATE TABLE' "$arquivo"; then
              # Se o arquivo tiver mais de um commit, configurar a variável
              if [ "$contagem_commits" -gt 1 ]; then
                echo "######################### entrou no laço"
                mais_de_um_commit=true
                break  # Não precisamos verificar os outros arquivos se já encontramos mais de um commit
              fi
            fi
          done

          # Validar se há mais de um commit em pelo menos um arquivo
          if [ "$mais_de_um_commit" == false ]; then
            echo "Erro: O pull request não tem mais de um commit. Crie um novo PR para garantir a ordem de execução"
            exit 1
          else
            echo "O pull request tem mais de um commit."
          fi
        fi
