name: Validar Extensão de Arquivos no Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited
    paths-ignore:
      - '.github/workflows/**'

jobs:
  validar-extensao:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Configurar variável de ambiente GH_TOKEN
      run: echo "GH_TOKEN=${{ secrets.GH_TOKEN }}" >> $GITHUB_ENV

    - name: Listar arquivos do pull request
      id: listar-arquivos
      run: |
        
          git diff --name-only HEAD^1 > files.txt
          cat files.txt

    - name: Verificar extensão de arquivos
      run: |
        tem_erro=false
        saida=""

        for arquivo in $(cat files.txt); do
          if [[ "$arquivo" != *.* ]]; then
            echo "############arquivo###########  $arquivo"
            echo "ERRO: O arquivo $arquivo não tem uma extensão. Todos os arquivos devem ter extensão."
            tem_erro=true
            saida="$saida$arquivo"$'\n'
            echo "##########saida########### $saida"
          fi
        done

        if [ "$tem_erro" = true ]; then
          echo "Enviando notificação para o Slack..."
          #curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"ERRO: Um ou mais arquivos no pull request não tem extensão. Todos os arquivos devem ter extensão.\n${saida}\"}" ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_MESSAGE="ERRO: Todos os arquivos devem ter extensão. PR: ${{ github.event.number }} - github.com/${GITHUB_REPOSITORY}/pull/${{ github.event.number }}/files (${{ github.base_ref }})\nUm ou mais arquivos no pull request não tem extensão:\n$saida"
          curl -X POST -H 'Content-type: application/json' --data '{"text":"'"$SLACK_MESSAGE"'"}' ${{ secrets.SLACK_WEBHOOK_URL }}
          PR_NUMBER=$(echo "${{ github.event.pull_request.html_url }}" | awk -F'/' '{print $NF}')
          REPO_OWNER=$(echo "${{ github.repository }}" | cut -d '/' -f 1)
          REPO_NAME=$(echo "${{ github.repository }}" | cut -d '/' -f 2)
          AUTHOR_NAME=${{ github.event.pull_request.user.login }}
          gh pr comment $PR_NUMBER -R $REPO_OWNER/$REPO_NAME --body "@$AUTHOR_NAME
          Um ou mais arquivos não tem extensão:
          ${saida}Por favor revisar."
          exit 1
        else
          echo "Todos os arquivos tem extensão."
        fi
